# Generated by Django 5.0.2 on 2024-03-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_paycancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='receipt_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterModelTable(
            name='paycancel',
            table='tbl_pay_cancel',
        ),
    ]
