# Generated by Django 5.0.2 on 2024-03-01 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_auto_20240301_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('letter_content', models.TextField()),
                ('status', models.BooleanField(default=1)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letter_receiver', to='member.member')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letter_sender', to='member.member')),
            ],
            options={
                'db_table': 'tbl_letter',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='letter.letter')),
            ],
            options={
                'db_table': 'tbl_received_letter',
            },
        ),
        migrations.CreateModel(
            name='SentLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=1)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='letter.letter')),
            ],
            options={
                'db_table': 'tbl_sent_letter',
            },
        ),
    ]
