# Generated by Django 5.0.2 on 2024-03-01 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('festival_title', models.TextField()),
                ('festival_content', models.TextField()),
                ('festival_price', models.FloatField()),
                ('festival_address', models.TextField()),
                ('festival_address_detail', models.TextField()),
                ('festival_location', models.TextField()),
                ('festival_start', models.DateField()),
                ('festival_end', models.DateField()),
                ('host_info', models.TextField()),
                ('host_phone', models.TextField()),
                ('provider_info', models.TextField()),
                ('provider_url', models.TextField()),
                ('thumbnail_path', models.ImageField(upload_to='festival/%Y/%m/%d')),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'tbl_festival',
            },
        ),
    ]
