# Generated by Django 5.0.2 on 2024-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_alter_festival_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='festival_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='festival_address_detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='festival_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='festival_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='festival_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='festival_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='host_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='host_phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='provider_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='provider_url',
            field=models.TextField(null=True),
        ),
    ]
