# Generated by Django 5.0.2 on 2024-03-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_alter_festival_festival_address_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='festival',
            managers=[
            ],
        ),
    ]
