# Generated by Django 5.0.2 on 2024-03-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_alter_festival_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='festival_category',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
