# Generated by Django 5.0.2 on 2024-03-01 00:05
from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(model_name='Member', name='member_type', field=models.CharField(max_length=10, null=False, blank=False)),
    ]
