# Generated by Django 5.0.2 on 2024-03-02 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20240301_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_id', models.TextField()),
                ('admin_password', models.TextField()),
                ('admin_name', models.TextField()),
            ],
            options={
                'db_table': 'tbl_admin_account',
            },
        ),
    ]
