# Generated by Django 5.0.2 on 2024-03-04 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_adminaccount'),
        ('teenplay_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_birth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='member.member'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MemberFavoriteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teenplay_server.category')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_member_favorite_category',
            },
        ),
    ]
