# Generated by Django 5.0.2 on 2024-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_member_birth_memberprofile_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_birth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_gender',
            field=models.SmallIntegerField(choices=[(0, '선택안함'), (1, '남성'), (2, '여성')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_marketing_agree',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_privacy_agree',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
