# Generated by Django 5.0.2 on 2024-03-11 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_member_member_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDeleteReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_reason', models.SmallIntegerField()),
                ('delete_text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'tbl_member_delete_reason',
            },
        ),
    ]
