# Generated by Django 5.0.2 on 2024-05-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0006_memberdeletereason"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="member_keyword1",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="member_keyword2",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="member_keyword3",
            field=models.TextField(null=True),
        ),
    ]
