# Generated by Django 5.0.2 on 2024-05-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0007_member_member_keyword1_member_member_keyword2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="member_recommended_activity_model",
            field=models.ImageField(null=True, upload_to="ai/%Y/%m/%d"),
        ),
    ]
