# Generated by Django 5.0.2 on 2024-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0008_member_member_recommended_activity_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_recommended_activity_model",
            field=models.TextField(null=True),
        ),
    ]
