# Generated by Django 5.0.2 on 2024-03-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('festival', '0002_alter_festival_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='festival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='festival.festival'),
        ),
    ]
