# Generated by Django 5.0.2 on 2024-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_festival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_address_detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_address_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_intro',
            field=models.TextField(null=True),
        ),
    ]
