# Generated by Django 5.0.2 on 2024-03-01 00:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice_title', models.TextField()),
                ('notice_content', models.TextField()),
                ('notice_type', models.SmallIntegerField(choices=[(0, '공지사항'), (1, ' 자주 묻는 질문')])),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'tbl_notice',
            },
        ),
    ]
