# Generated by Django 5.0.2 on 2024-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
