# Generated by Django 5.0.2 on 2024-03-03 18:14

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_club_info'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clubmember',
            managers=[
                ('enabled_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
