# Generated by Django 5.0.2 on 2024-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubmember_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_info',
            field=models.TextField(null=True),
        ),
    ]
