# Generated by Django 5.0.2 on 2024-05-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0005_alter_clubpost_managers_alter_clubpostreply_managers_and_more"),
        ("teenplay_server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="club_region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="teenplay_server.region",
            ),
        ),
    ]
