# Generated by Django 5.0.2 on 2024-05-17 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0006_club_club_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubpost",
            name="category",
        ),
    ]
